#!/bin/sh
if git diff --cached --name-only | grep -q ".env"; then
  echo "Error: You are trying to commit a .env file!"
  echo "Please remove it from the staging area using 'git reset HEAD .env' and add it to .gitignore."
  exit 1
fi
